apiVersion: v1

kind: Secret
metadata:
  name: mysql-credentials
  labels:
    "bookstore/example": bookstore
type: Opaque
# Encode secrets exactly like this from your command line
# if you use a different command, you will run into errors with newlines
data:
  # root password for MySQL
  # the actual password is varMyRootPass
  # echo -n mypassword | base64
  rootpw: bXlwYXNzd29yZA==
  # user for MySQL
  # the actual username is varMyDBUser
  # echo -n operator | base64
  user: b3BlcmF0b3I=
  # password for the second MySQL user
  # the actual password is varMyDBPass
  # echo -n adminadmin | base64
  password: YWRtaW5hZG1pbg==